### ISSUE TITLE
상황에 맞는 그림 가져오기

### ISSUE THREAD

**Issue by freejin23** [freejin23/Randomstate_42#7]

**Comment by freejin23** [comment]
https://miro.medium.com/max/1838/1*aEBa5d9idUQDAf2fzvuR_w.jpeg
요거 어떠신가요?

**Comment by leesulpark** [comment]
못 보고 클로즈해버렸습니다! :) 두 번째 이터레이션에서는 시간을 가지고 천천히 리뷰해보아요 후하히호
